### PR TITLE
Enable routeback on OVPN zone

### PR DESCRIPTION
**Pull request by gsanchietti**
Allow network traffic flow between roadwarrior and remote networks connected to OpenVPN tunnels.
The traffic is blocked by default from built-in `sfilter` Shorewall chain.

To enable it:
```
config setprop firewall VpnPolicy permissive
```

This PR also allows the creation of firewall rules involving hosts inside the remote tunnel network.
It works out-of-the box if the firewall is running the tunnel server.
If the firewall is acting as a tunnel client, the `RemoteNetworks` property must be set, otherwise host objects used inside firewall rules will not be correctly located inside the `ovpn` zone. In this case, just add the `RemoteNetworks` property to the tunnel:
```
db vpn setprop tunnelclient RemoteNetworks 192.168.0.0/24,192.168.1.0/24
```

**Usage scenario**

A firewall configured with:
- net2net tunnel with a remote venue
- roadwarrior enabled with a client connected from remote location
- the roadwarrior client want to reach the venue behind the tunnel

Additional steps:
- if the firewall is the tunnel server, add the roadwarrior network inside the "Local networks"
- if the firewall is the tunnel client, add the roadwarrior network inside the "Remote networks" of the tunnel server in the remote venute
- add the remote network to the roadwarrior routes

NethServer/dev#6136

### CODE REVIEW

**Comment by cotosso** [comment]
Very good, we can manage properly and effectively these scenarios with just little modifications and without risks of regression. 

I suggest to add a "settings" section in VPN panel where we can enable routeback option for the openvpn interfaces, I think it's safer to leave it disabled by default.

About the OpenVPN **Tunnel client** we need to know the remote network only to create firewall rules, I suggest to reuse the same field we already use when in _p2p mode_ (called "remote network"), showing it also in _subnet mode_ but in the advanced section with a slightly different reference and an info box.
e.g. label : remote network (optional for firewall rules)
       info: Remote network is needed only if you want to create firewall rules on this specific traffic.

**Review by cotosso — APPROVED** [review]

**Review by filippocarletti — CHANGES_REQUESTED** [review]
For consistency, routeback should be enabled by default.
If the remote subnet is connected via an ipsec tunnel routing is enabled by default.

**Comment by gsanchietti** [comment]
IIUC the proposal is to change the current behavior of new and existing machines?

The routing between IPSec and OpenVPN is not affected by this change.
If the `routeback` option must be the default also for old installations (I strongly disagree on this), we can totally remove the prop and just change the default inside the template.

**Comment by filippocarletti** [comment]
> IIUC the proposal is to change the current behavior of new and existing machines?

Yes

**Comment by gsanchietti** [comment]
> > IIUC the proposal is to change the current behavior of new and existing machines?
> 
> Yes

I really do not like changing behavior on existing machines: it breaks user expectations.

But if @cotosso confirms it, I will go down this path.

**Comment by cotosso** [comment]
Considering that this feature is not in very common use, even more and more frequent, I think it is better to leave the default as it is now (routeback disabled), both from the point of view of security and clarity for the administrator who manages the firewall.

To allow traffic to pass there is a configuration to do, which is **very simple** (a switch), but necessary.
On the other hand it is true that routing between IPsec and OpenVPN is allowed by default, but in that case it is still **necessary** to create a firewall rule to allow traffic between the ovpn and ivpn zone, otherwise the traffic cannot pass.

**Comment by gsanchietti** [comment]
So adding the new `Routeback` option, disabled by default, is consistence with the actual configuration also for IPSec.

If the patch gets accepted, the admin will:
- set Rotueback to enabled to allow traffic from roadwarrior to openvpn tunnel
- create a firewall rule to allow traffic from roadwarrior to ipsec tunnel

It looks consistent to me, even if it requires a little bit of documentation.

**Comment by gsanchietti** [comment]
I can also propose a different solution (not tested).

Rename the `Routeback` to something like `Policy`:
- if `Policy` is set to `permissive`: add routeback option, add a policy to allow traffic between ivpn and ovpn
- if `Policy` is set to `strict`: do nothing, current default

What do you think @filippocarletti ?

**Review by filippocarletti — APPROVED** [review]

**Pull request merged**
