### PR TITLE
hotsync. avoid error on slave host

### PR DESCRIPTION
**Pull request by federicoballarini**
Avoid error on slave host while saving config.
Refer to https://github.com/NethServer/dev/issues/6010

### CODE REVIEW

**Comment by gsanchietti** [comment]
What problem are you trying to solve exactly?
If the package is installed, the database is already in place and the modified code shouldn't raise any error.
It seems you're trying to silcence the error itself and not the cause.

Also, bear in mind that any modification to core for extra packages is **highly** discouraged.

**Review by gsanchietti — CHANGES_REQUESTED** [review]
Avoid changes to core code for non-core package.

**Comment by federicoballarini** [comment]
> What problem are you trying to solve exactly?
> If the package is installed, the database is already in place and the modified code shouldn't raise any error.
> It seems you're trying to silcence the error itself and not the cause.
> 
> Also, bear in mind that any modification to core for extra packages is **highly** discouraged.

Logs on slave host with openvpn and ipsec tunnels synced report this:

```
Dec 22 20:21:20 fw2 esmith::event[13934]: ERROR in /etc/e-smith/templates//etc/ **shorewall** /rules/90openvpn_tunnels: Program fragment delivered error <<Can't call method "get_all_by_prop" on an undefined value at /etc/e-smith/templates//etc/ **shorewall** /rules/90openvpn_tunnels line 8.>> at template line 4
Dec 22 20:21:20 fw2 esmith::event[13934]: ERROR: Template processing failed for //etc/ **shorewall** /rules: 1 fragment generated errors
Dec 22 20:28:59 fw2 esmith::event[17217]: ERROR in /etc/e-smith/templates//etc/ **shorewall** /hosts/20green: Program fragment delivered error <<Can't call method "get_all_by_prop" on an undefined value at /usr/share/perl5/vendor_perl/NethServer/TrustedNetworks/IpSec.pm line 38.>> at template line 1
Dec 22 20:28:59 fw2 esmith::event[17217]: ERROR: Template processing failed for //etc/ **shorewall** /hosts: 1 fragment generated errors
```

**Comment by gsanchietti** [comment]
> Logs on slave host with openvpn and ipsec tunnels synced report this:

You need to find the reason why the db is not available while the expand-template is executed and try to fix it.
Otherwise, if the problem is just cosmetic and get fixed when the slave is promoted to master, just ignore it ;)

**Pull request closed without merging**
