### PR TITLE
Custom EOL for renew and certificate generation

### PR DESCRIPTION
**Pull request by stephdl**
https://github.com/NethServer/dev/issues/6145

### CODE REVIEW

**Review by edospadoni — APPROVED** [review]

**Review by gsanchietti — APPROVED** [review]
I hoped a for a better variable name like `duration` or at least a camel case form `certEol`, but that's a matter of personal taste.

**Comment by edospadoni** [comment]
What do you think @stephdl can you change the variable name?

**Comment by stephdl** [comment]
no problem, lets go to `duration`

**Comment by stephdl** [comment]
done @edospadoni

**Comment by gsanchietti** [comment]
Thank you! :kiss:

**Review by edospadoni — APPROVED** [review]

**Pull request merged**
