### PR TITLE
New policy : login+certs+otp (forced)

### PR DESCRIPTION
**Pull request by stephdl**
https://github.com/NethServer/dev/issues/6112

install the rpm
enable otp for the user in the setting user page 
enable otp globally in openvpn 

```
config setprop openvpn@host-to-net AuthMode certificate-otp
signal-event nethserver-openvpn-save
```

create a link to the secret to enable otp & the user

```
ln -s /var/lib/nethserver/home/stephane/.2fa.secret /var/lib/nethserver/home/stephane/.2fa_openvpn.secret
signal-event otp-save
```

download the certificate for the client, we have changed the  renegotiation to 0s (reneg-sec 0) and now even with a certificate exchange we must say to the client prompt for a password (else it fails), so **it means in the client side to set a login+password+certificates**

Set username +password+certs in the client configuration . It is needed because we need to say to openvpn it must wait after a OTP pin. When the password prompts, write the otp code OR if your user is not forced to OTP, a pseudo password is needed but it can be saved (I do not like this)

## Know issues

If your user is not forced  to OTP (eg ~/.2fa_openvpn.secret is NOT a valid link), we need to send a login name with a pseudo password, this login is checked in /etc/nethserver/openvpn.cockpit.force, if not present, then you are allowed to login without otp pin, if present you must valid a good OTP pin. 

To avoid the pseudo code we could force everybody to certs+OTP

### CODE REVIEW

**Comment by gsanchietti** [comment]
Without a verification between certificate CN and PAM user, OTP without enforcing really doesn't make sense.
Since this is an internal and really hard to documento for a non techincal user, I'd leave no choice of freedom to the admin.

In the end, I think we should always enforce OTP when the `certificate + OTP` authentication mode has been selected.
The same applies also to GA.

**Comment by stephdl** [comment]
Certificates are now forced to OTP when `OtpStatus` === `enabled` and `AuthMode` === `certificate`

**Comment by stephdl** [comment]
back to this policy optional, with the PR https://github.com/NethServer/nethserver-openvpn/pull/59 it is now possible

**Comment by stephdl** [comment]
We have a new policy : 'login+certficate+otp'. @gsanchietti @cotosso 

We control that the login doesn't mismatch with the common name of the certificate(I rebased on master), if equal we accept, the otp can be forced or not.

We have a little issue due to the fact that we do not force users to this policy, if someone is not forced  (eg the name is not inside /etc/nethserver/openvpn.otp.force) it needs to provide a login that matches the CN and a dummy password that can be saved in the openvpn client. If the remote user try to use simply a certificate configuration, openvpn stop and wait a username/password

`TLS Error: Auth Username/Password was not provided by peer`

**Comment by gsanchietti** [comment]
> We have a little issue due to the fact that we do not force users to this policy, if someone is not forced (eg the name is not inside /etc/nethserver/openvpn.otp.force) it needs to provide a login that matches the CN and a dummy password that can be saved in the openvpn client. If the remote user try to use simply a certificate configuration, openvpn stop and wait a username/password

Since we introduced a new authentication schema, I think that users should be forced to it.
As an example, if the admin selects user+password, the user is forced to enter both.
So I think the same behavior should be applied here: if the authentication schema is certificate+OTP, the user must provide both, otherwise the authentication must fail.

**Comment by stephdl** [comment]
ok it fixes the problem of the dummy password, I prefer it also

**Review by gsanchietti — APPROVED** [review]

**Pull request merged**
